version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12.9.1

commands:
  install_packages:
    description: Install npm dependencies
    steps:
      # @TODO add caching here
      - run:
          name: Install dependencies
          command: npm i


jobs:
  rln-utilities-deps-and-tests:
    executor: node12
    steps:
      - checkout
      - run: cd packages/restlessness-utilities
      - install_packages
      - run:
          name: Run tests
          command: npm run test

  rln-utilities-publish:
    executor: node12
    steps:
      - checkout
      - run: cd packages/restlessness-utilities
      - install_packages
      - run:
          name: Npm publish
          command: node ../scripts/npm-publish.js
          working_directory: packages/restlessness-utilities

workflows:
    rln-utilities:
      jobs:
        - rln-utilities-deps-and-tests
        - rln-utilities-publish:
            requires:
              - rln-utilities-deps-and-tests
            filters:
              tags:
                only: /^ci-test@restlessness/utilities/v(\d+)\.(\d+)\.(\d+)$/

