version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12.9.1

commands:
  install_packages:
    description: Install npm dependencies
    parameters:
      working_directory:
        type: string
    steps:
      # @TODO add caching here
      - run:
          name: Install dependencies
          command: npm i
          working_directory: << parameters.working_directory >>

  deps_and_tests:
    description: Install dependencies and run tests
    parameters:
      working_directory:
        type: string
    steps:
      - install_packages:
          working_directory: << parameters.working_directory >>
      - run:
          name: Run tests
          command: npm test
          working_directory: << parameters.working_directory >>

  npm_publish:
    description: Run prepublsh script, set version and publish
    parameters:
      working_directory:
        type: string
    steps:
      - run:
          name: Set package.json version from git tag
          command: |
            # resolve scripts folder location from working directory
            SCRIPTS_PATH=$(node -e "
              const path = require('path')
              const from = '${CIRCLE_WORKING_DIRECTORY}/<< parameters.working_directory >>'
              const to = '${CIRCLE_WORKING_DIRECTORY}/scripts'
              console.log(path.relative(from, to))
            ")
            node "${SCRIPTS_PATH}/set-version-from-tag.js"
          working_directory: << parameters.working_directory >>
      - run:
          name: Publish package
          command: echo 'npm run publish' # @TODO remove echo when workflow is done
          working_directory: << parameters.working_directory >>

  deps_and_publish:
    description: Install dependencies and publish package
    parameters:
      working_directory:
        type: string
    steps:
      - install_packages:
          working_directory: << parameters.working_directory >>
      - npm_publish:
          working_directory: << parameters.working_directory >>


jobs:
  rln-utilities-tests:
    executor: node12
    steps:
      - checkout
      - deps_and_tests:
          working_directory: packages/restlessness-utilities

  rln-utilities-publish:
    executor: node12
    steps:
      - checkout
      - deps_and_publish:
          working_directory: packages/restlessness-utilities

  rln-core-tests:
    executor: node12
    steps:
      - checkout
      - deps_and_tests:
          working_directory: packages/restlessness-utilities

  rln-core-publish:
    executor: node12
    steps:
      - checkout
      - deps_and_publish:
          working_directory: packages/restlessness-utilities


workflows:
    rln-utilities:
      jobs:
#        - rln-utilities-tests:
#            filters:
#              tags:
#                only: /.*/
        - rln-utilities-publish:
#            requires:
#              - rln-utilities-tests
            filters:
              tags:
                # only: /^ci-test@restlessness/utilities/v(\d+)\.(\d+)\.(\d+)$/
                only: /^ci-test.*/
#              branches:
#                ignore: /.*/


#    rln-core:
#      jobs:
#        - rln-core-tests:
#            filters:
#              tags:
#                only: /.*/
#        - rln-core-publish:
#            requires:
#              - rln-core-tests
#            filters:
#              tags:
#                # only: /^ci-test@restlessness/core/v(\d+)\.(\d+)\.(\d+)$/
#                only: /.*ci-test.*/
#              branches:
#                ignore: /.*/

