version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12.9.1

commands:
  install_packages:
    description: Install npm dependencies
    parameters:
      working_directory:
        type: string
    steps:
      # @TODO add caching here
      - run:
          name: Install dependencies
          command: npm i
          working_directory: << parameters.working_directory >>

  npm_publish:
    description: Run prepublsh script, set version and publish
    parameters:
      working_directory:
        type: string
    steps:
      - run:
          name: Set package.json version from git tag
          command: |
            # resolve scripts folder location from working directory
            SCRIPTS_PATH=$(node -e "
              const path = require('path')
              const from = '${CIRCLE_WORKING_DIRECTORY}/<< parameters.working_directory >>'
              const to = '${CIRCLE_WORKING_DIRECTORY}/scripts'
              console.log(path.relative(from, to))
            ")
            node "${SCRIPTS_PATH}/set-version-from-tag.js"
          working_directory: << parameters.working_directory >>
      - run:
          name: Publish package
          command: echo 'npm run publish' # @TODO remove echo when workflow is done
          working_directory: << parameters.working_directory >>


jobs:
  rln-utilities-deps-and-tests:
    executor: node12
    steps:
      - checkout
      - install_packages:
          working_directory: packages/restlessness-utilities
      - run:
          name: Run tests
          command: npm test
          working_directory: packages/restlessness-utilities

  rln-utilities-publish:
    executor: node12
    steps:
      - checkout
      - install_packages:
          working_directory: packages/restlessness-utilities
      - npm_publish:
          working_directory: packages/restlessness-utilities

  rln-core-deps-and-tests:
    executor: node12
    steps:
      - checkout
      - install_packages:
          working_directory: packages/restlessness-core
      - run:
          name: Run tests
          command: npm test
          working_directory: packages/restlessness-core

  rln-core-publish:
    executor: node12
    steps:
      - checkout
      - install_packages:
          working_directory: packages/restlessness-core
      - npm_publish:
          working_directory: packages/restlessness-core


workflows:
    rln-utilities:
      jobs:
        - rln-utilities-deps-and-tests:
            filters:
              tags:
                only: /.*/
        - rln-utilities-publish:
            requires:
              - rln-utilities-deps-and-tests
            filters:
              tags:
                only: /^ci-test@restlessness/utilities/v(\d+)\.(\d+)\.(\d+)$/

    rln-core:
      jobs:
        - rln-core-deps-and-tests:
            filters:
              tags:
                only: /.*/
        - rln-core-publish:
            requires:
              - rln-core-deps-and-tests
            filters:
              tags:
                only: /^ci-test@restlessness/core/v(\d+)\.(\d+)\.(\d+)$/

