version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12.9.1

jobs:
  rln-utilities-deps-and-tests:
    executor: node12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
          working_directory: packages/restlessness-utilities
      - run:
          name: Run Tests
          command: npm run test
          working_directory: packages/restlessness-utilities

  rln-utilities-publish:
    executor: node12
    steps:
      - run:
          name: Npm publish
          command: node ../scripts/npm-publish.js
          working_directory: packages/restlessness-utilities

workflows:
    rln-utilities:
      jobs:
        - rln-utilities-deps-and-tests
        - rln-utilities-publish:
            requires:
              - rln-utilities-deps-and-tests
            filters:
              tags:
                only: /^ci-test@restlessness/utilities/v(\d+)\.(\d+)\.(\d+)$/

