version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12.9.1

orbs:
  node: circleci/node@1.1.6

jobs:
  rln-utilities-deps-and-tests:
    executor: node12
    steps:
      - checkout
      - run: cd packages/restlessness-utilities
      - node/install-packages
      - run:
          name: Run Tests
          command: npm run test

  rln-utilities-publish:
    executor: node12
    steps:
      - run:
          name: Npm publish
          command: node ../scripts/npm-publish.js

workflows:
    rln-utilities:
      jobs:
        - rln-utilities-deps-and-tests
        - rln-utilities-publish:
            requires:
              - rln-utilities-deps-and-tests
            filters:
              tags:
                only: /^ci-test@restlessness/utilities/v(\d+)\.(\d+)\.(\d+)$/

