version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12.9.1

commands:
  install_packages:
    description: Install npm dependencies
    parameters:
      working_directory:
        type: string
    steps:
      # @TODO add caching here
      - run:
          name: Install dependencies
          command: npm i
          working_directory: << parameters.working_directory >>

jobs:
  rln-utilities-deps-and-tests:
    executor: node12
    steps:
      - checkout
      - install_packages:
          working_directory: packages/restlessness-utilities
      - run:
          name: Run tests
          command: npm run test
          working_directory: packages/restlessness-utilities

  rln-utilities-publish:
    executor: node12
    steps:
      - checkout
      - install_packages:
          working_directory: packages/restlessness-utilities
      - run:
          name: Npm publish
          command: node ../../scripts/npm-publish.js
          working_directory: packages/restlessness-utilities

workflows:
    rln-utilities:
      jobs:
        - rln-utilities-deps-and-tests
        - rln-utilities-publish:
            requires:
              - rln-utilities-deps-and-tests
            filters:
              tags:
                only: /^ci-test@restlessness/utilities/v(\d+)\.(\d+)\.(\d+)$/

